apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: default-ns-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
  - host: psychic-eureka-4qggj6wqvjrvcvgj-31897.app.github.dev
    http:
      paths:
      - path: /api/backend/
        pathType: Prefix
        backend:
          service:
            name: backend-prod-svc
            port:
              number: 8000